spring:
    datasource:
        username: ""
        password: ""
        url: "jdbc:mysql://localhost:3306/YOUR_DATABASE_NAME?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useTimezone=true&serverTimezone=UTC"